# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3f0b4ee9f49512079e175a305ec12ab705f33c1f7108bf2850959ff513b46e39bd88e24005c771af7e0f2b1a5f508cfb31ac2820f8b0e0d202eda74ac1bf6e

  facebook_key: "983534158420710"
  facebook_secret: "1b3838a42b1b383af5ce0c81b6726486"

  twitter_key: "jXOzKH6NWkE6WnD5aE632Xesq"
  twitter_secret: "Z3f7NiPiBWhtJFq34Uuf1z2cYbJmfbddNQPhjdIpe7oAP5EWyH"

  github_key: "0368f6d52df41325a2a8"
  github_secret: "7d966ad3752b101266f0ba33b73f8b7d60f8bab5"

  linkedin_key: "77p1hyu0gjifql"
  linkedin_secret: "C7jbTZ0eIOmcR26X"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

test:
  secret_key_base: fadd8d32344b6c5bbf1536b505bc7ebc440962687c116e767b7cddf7ba1d1c6afae7d6c7966c00dd5586712545b657bb5f053958cda3790202ebd1f70cd5485c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  facebook_key: "983534158420710"
  facebook_secret: "1b3838a42b1b383af5ce0c81b6726486"

  twitter_key: "jXOzKH6NWkE6WnD5aE632Xesq"
  twitter_secret: "Z3f7NiPiBWhtJFq34Uuf1z2cYbJmfbddNQPhjdIpe7oAP5EWyH"

  github_key: "0368f6d52df41325a2a8"
  github_secret: "7d966ad3752b101266f0ba33b73f8b7d60f8bab5"

  linkedin_key: "77p1hyu0gjifql"
  linkedin_secret: "C7jbTZ0eIOmcR26X"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
